package view;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import model.ConfigBean;
import model.Configuration;
import util.Utility;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by jishshi on 2015/6/10.
 */
public class MyFrame extends JFrame {
    private JPanel myPanel;
    private JButton exportBtn;
    private JLabel exportMsg;
    private JTabbedPane tabbedPane1;
    private ConfigBean configBean;
    private Configuration configuration;

    public MyFrame(String title, int width, int height) {
        super(title);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(width, height);                          // 设置窗口大小
        Dimension displaySize = Toolkit.getDefaultToolkit().getScreenSize(); // 获得显示器大小对象
        Dimension frameSize = this.getSize();             // 获得窗口大小对象
        if (frameSize.width > displaySize.width)
            frameSize.width = displaySize.width;           // 窗口的宽度不能大于显示器的宽度
        this.setLocation((displaySize.width - frameSize.width) / 3,
                (displaySize.height - frameSize.height) / 4); // 设置窗口居中显示器显示
        //frame.pack();     //Causes this Window to be sized to fit the preferred size and layouts of its subcomponents
        this.setResizable(false);
        this.setContentPane(myPanel);
        //init tabbedPanel
        final SptForm sptForm = new SptForm();
        tabbedPane1.addTab("标准贯入实验", sptForm.getFormPanel());

        final DstForm dstForm = new DstForm();
        tabbedPane1.addTab("动力触探实验", dstForm.getFormPanel());
        tabbedPane1.setVisible(true);
        myPanel.setVisible(true);

        configBean = new ConfigBean();
        configuration = new Configuration();

        //initial bean
        Utility.model2bean(configBean, configuration);
        sptForm.setData(configBean);
        dstForm.setData(configBean);

        exportBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser jfc = new JFileChooser();  //新建一个选择文件夹的类型
                jfc.setDialogTitle("导出配置文件");
                jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) { //开始选择路径
                    String path = jfc.getSelectedFile().getAbsolutePath() + "/config.ser";
                    System.out.println(path);
                    sptForm.getData(configBean);
                    dstForm.getData(configBean);

                    Utility.bean2model(configuration, configBean);
                    if (Utility.exportConfig(configuration, path)) {
                        exportMsg.setText("导出成功(路径：" + path + ")");
                    } else {
                        exportMsg.setText("导出失败，请检查。");
                    }
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myPanel = new JPanel();
        myPanel.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,bottom:3dlu:noGrow,center:8px:noGrow"));
        exportBtn = new JButton();
        exportBtn.setText("导出");
        CellConstraints cc = new CellConstraints();
        myPanel.add(exportBtn, cc.xy(5, 5));
        exportMsg = new JLabel();
        exportMsg.setFont(new Font(exportMsg.getFont().getName(), exportMsg.getFont().getStyle(), 14));
        exportMsg.setText("");
        exportMsg.putClientProperty("html.disable", Boolean.FALSE);
        myPanel.add(exportMsg, cc.xy(7, 5));
        tabbedPane1 = new JTabbedPane();
        tabbedPane1.setBackground(new Color(-6047008));
        myPanel.add(tabbedPane1, cc.xyw(1, 3, 9, CellConstraints.DEFAULT, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myPanel;
    }
}
